travis:
  secure:
    BINSTAR_TOKEN: FR0jWpp09OYoIEWCIhRa17rd67DoNLicEEsI3d5/V9hcCTc35IsNO3W9fCpuXTeAYQwwdyS9VqL/thEy/uslWYPC9sF0c55dyF/VZO5L8p91dIrdzW2Fp7rwXps28m00gfgOXS8Pgx1oYiX9bN0eO0EFlIRiduQpgZnW+8Q1lb/4ZKq6kkwEq3CamyJQEb8zEBoRjC8cCC+WPLJEtfP5v1it/R8Te14uDaqi4qMkqOUvk0Ott8UmbsJuZUjXrg1h8i9hvTyNmMbS3snwcLd/DKidfJJv5f3Tw6yfyV4hZiPpHbmIXqRrL5PPqbGR4W6ZJfQPm0/fZsU8ER0vIreaPb8pUOL9GF8N/RGc7lk7ntCBzSAJ55Rzn6KwicG2i60kTYx7D06fQ37QpVpY0gQLfMGbSW9x2d7Os05/WhofnFm6bsdOa4IW9ARgYdSB0YJNVRx2C1zdMXhwRp8pfTSGyVK8ZK3qFvQy3/etAVDMabNiYe+7ZewQ4gpnK8JAO9AnJoc64W1FU+rTr+f7hAS2BVffsi2ifc5DJbDSNHJkAFqhtdZ5kY+fDX/6bo8k5qLVBFkMCqceCDElZkk4iON2yg6SGR0j8mCJZ4lyHUMg1eykjSPlRCQRL14YqI69C5yimD7cCvLHLJbcqUPmdSDtw5Q62lIt8hYgr4bPhFO07hs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
